version: "3.7"
services:
  cloudbeaver:
    container_name: cloudbeaver
    image: dbeaver/cloudbeaver:latest
    ports:
      - ${APP_PORT}:8978
    volumes:
      - ${APP_DATA_DIR}/data:/opt/cloudbeaver/workspace
    environment:
      - TZ=${TZ}
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.cloudbeaver-web-redirect.redirectscheme.scheme: https
      traefik.http.services.cloudbeaver.loadbalancer.server.port: 8978
      # Web
      traefik.http.routers.cloudbeaver-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.cloudbeaver-insecure.entrypoints: web
      traefik.http.routers.cloudbeaver-insecure.service: cloudbeaver
      traefik.http.routers.cloudbeaver-insecure.middlewares: cloudbeaver-web-redirect
      # Websecure
      traefik.http.routers.cloudbeaver.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.cloudbeaver.entrypoints: websecure
      traefik.http.routers.cloudbeaver.service: cloudbeaver
      traefik.http.routers.cloudbeaver.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.cloudbeaver-local-insecure.rule: Host(`cloudbeaver.${LOCAL_DOMAIN}`)
      traefik.http.routers.cloudbeaver-local-insecure.entrypoints: web
      traefik.http.routers.cloudbeaver-local-insecure.service: cloudbeaver
      traefik.http.routers.cloudbeaver-local-insecure.middlewares: cloudbeaver-web-redirect
      # Local domain secure
      traefik.http.routers.cloudbeaver-local.rule: Host(`cloudbeaver.${LOCAL_DOMAIN}`)
      traefik.http.routers.cloudbeaver-local.entrypoints: websecure
      traefik.http.routers.cloudbeaver-local.service: cloudbeaver
      traefik.http.routers.cloudbeaver-local.tls: true
      runtipi.managed: true
