version: '3.8'

services:
  pterodactyl-wings-perms:
    container_name: pterodactyl-wings-perms
    image: alpine:3.21
    restart: "no"
    network_mode: none
    command:
      - /bin/sh
      - -c
      - mkdir -p /var/lib/pterodactyl/volumes /var/lib/pterodactyl/archives /var/lib/pterodactyl/backups && chown 988:988 /var/lib/pterodactyl /var/lib/pterodactyl/volumes /var/lib/pterodactyl/archives /var/lib/pterodactyl/backups && chmod 755 /var/lib/pterodactyl /var/lib/pterodactyl/volumes /var/lib/pterodactyl/archives /var/lib/pterodactyl/backups
    volumes:
      - /var/lib/pterodactyl:/var/lib/pterodactyl

  pterodactyl-wings:
    container_name: pterodactyl-wings
    image: ghcr.io/pterodactyl/wings:latest
    restart: unless-stopped
    depends_on:
      pterodactyl-wings-perms:
        condition: service_completed_successfully
    ports:
      - ${APP_PORT}:8080
      - ${TIPI_PTERODACTYL_WINGS_SFTP_PORT}:2022
    networks:
      - tipi_main_network
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${APP_DATA_DIR}/etc:/etc/pterodactyl
      - /var/lib/pterodactyl:/var/lib/pterodactyl
      - ${APP_DATA_DIR}/logs:/var/log/pterodactyl
      - ${APP_DATA_DIR}/tmp:/tmp/pterodactyl
      - ${APP_DATA_DIR}/run:/run/wings
    labels:
      traefik.enable: true
      traefik.http.middlewares.pterodactyl-wings-web-redirect.redirectscheme.scheme: https
      traefik.http.services.pterodactyl-wings.loadbalancer.server.port: 8080
      traefik.http.routers.pterodactyl-wings-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.pterodactyl-wings-insecure.entrypoints: web
      traefik.http.routers.pterodactyl-wings-insecure.service: pterodactyl-wings
      traefik.http.routers.pterodactyl-wings-insecure.middlewares: pterodactyl-wings-web-redirect
      traefik.http.routers.pterodactyl-wings.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.pterodactyl-wings.entrypoints: websecure
      traefik.http.routers.pterodactyl-wings.service: pterodactyl-wings
      traefik.http.routers.pterodactyl-wings.tls.certresolver: myresolver
      traefik.http.routers.pterodactyl-wings-local-insecure.rule: Host(`pterodactyl-wings.${LOCAL_DOMAIN}`)
      traefik.http.routers.pterodactyl-wings-local-insecure.entrypoints: web
      traefik.http.routers.pterodactyl-wings-local-insecure.service: pterodactyl-wings
      traefik.http.routers.pterodactyl-wings-local-insecure.middlewares: pterodactyl-wings-web-redirect
      traefik.http.routers.pterodactyl-wings-local.rule: Host(`pterodactyl-wings.${LOCAL_DOMAIN}`)
      traefik.http.routers.pterodactyl-wings-local.entrypoints: websecure
      traefik.http.routers.pterodactyl-wings-local.service: pterodactyl-wings
      traefik.http.routers.pterodactyl-wings-local.tls: true
      runtipi.managed: true
