version: '3.8'
services:
  netdata:
    container_name: netdata
    image: netdata/netdata:stable
    restart: unless-stopped
    ports:
      - ${APP_PORT}:19999
    networks:
      - tipi_main_network
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_DATA_DIR}/config:/etc/netdata
      - ${APP_DATA_DIR}/lib:/var/lib/netdata
      - ${APP_DATA_DIR}/cache:/var/cache/netdata
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.netdata-web-redirect.redirectscheme.scheme: https
      traefik.http.services.netdata.loadbalancer.server.port: 19999
      # Web
      traefik.http.routers.netdata-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.netdata-insecure.entrypoints: web
      traefik.http.routers.netdata-insecure.service: netdata
      traefik.http.routers.netdata-insecure.middlewares: netdata-web-redirect
      # Websecure
      traefik.http.routers.netdata.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.netdata.entrypoints: websecure
      traefik.http.routers.netdata.service: netdata
      traefik.http.routers.netdata.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.netdata-local-insecure.rule: Host(`netdata.${LOCAL_DOMAIN}`)
      traefik.http.routers.netdata-local-insecure.entrypoints: web
      traefik.http.routers.netdata-local-insecure.service: netdata
      traefik.http.routers.netdata-local-insecure.middlewares: netdata-web-redirect
      # Local domain secure
      traefik.http.routers.netdata-local.rule: Host(`netdata.${LOCAL_DOMAIN}`)
      traefik.http.routers.netdata-local.entrypoints: websecure
      traefik.http.routers.netdata-local.service: netdata
      traefik.http.routers.netdata-local.tls: true
      runtipi.managed: true
